import HeroImage from "../assets/HeroImage.png";

export const CARD_BG = [
{ id: 1, bgcolor: 'linear-gradient(135deg, #d1fae5 0%, #a7f3d0 100%)' }, // green
  { id: 2, bgcolor: 'linear-gradient(135deg, #fef3c7 0%, #fde68a 100%)' }, // yellow
  { id: 3, bgcolor: 'linear-gradient(135deg, #dbeafe 0%, #bfdbfe 100%)' }, // blue
  { id: 4, bgcolor: 'linear-gradient(135deg, #ffe4e6 0%, #fecdd3 100%)' }, // pink
  { id: 5, bgcolor: 'linear-gradient(135deg, #e0f2fe 0%, #bae6fd 100%)' }, // sky
  { id: 6, bgcolor: 'linear-gradient(135deg, #e5e7eb 0%, #d1d5db 100%)' }, // gray
  { id: 7, bgcolor: 'linear-gradient(135deg, #f5d0fe 0%, #e9d5ff 100%)' }, // purple
  { id: 8, bgcolor: 'linear-gradient(135deg, #ccfbf1 0%, #99f6e4 100%)' }, // teal
  { id: 9, bgcolor: 'linear-gradient(135deg, #ede9fe 0%, #ddd6fe 100%)' }, // indigo
  { id: 10, bgcolor: 'linear-gradient(135deg, #fee2e2 0%, #fecaca 100%)' }, // red
];
export const APP_FEATURES = [
    {
      id: '1',
    title: "Tailored just for you",
    description:
      "Get interview questions and model answers based on your role, experience, and specific focus areas — no generic practice here.",
  },
    {
      id: '2',
    title: "Learn at Your Own Pace",
    description:
      "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered detailed explanations.",
  },
    {
      id: '3',
    title: "Capture Your Insights",
    description:
      "Add personal notes to any question and pin important ones to the top — making your learning more organized and impactful.",
  },
  {id: '4',
    title: "Understand the 'Why' Behind Answers",
    description:
      "Beyond just answers — unlock detailed concept explanations generated by AI, helping you truly master each topic.",
  },
  {id: '5',
    title: "Save, Organize, and Revisit",
    description:
      "Easily save your interview sets, organize them neatly in your dashboard, and pick up your preparation right where you left off.",
  },
];


export const HERO_IMG = HeroImage;
